<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-05-25 at 23:44:38.
 */
class PdoGsbTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PdoGsb
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PdoGsb;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PdoGsb::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getPdoGsb
     * @todo   Implement testGetPdoGsb().
     */
    public function testGetPdoGsb() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getInfosVisiteur
     * @todo   Implement testGetInfosVisiteur().
     */
    public function testGetInfosVisiteur() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getInfosComptable
     * @todo   Implement testGetInfosComptable().
     */
    public function testGetInfosComptable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getLesFraisHorsForfait
     * @todo   Implement testGetLesFraisHorsForfait().
     */
    public function testGetLesFraisHorsForfait() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getNbjustificatifs
     * @todo   Implement testGetNbjustificatifs().
     */
    public function testGetNbjustificatifs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getLesFraisForfait
     * @todo   Implement testGetLesFraisForfait().
     */
    public function testGetLesFraisForfait() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getLesIdFrais
     * @todo   Implement testGetLesIdFrais().
     */
    public function testGetLesIdFrais() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::majFraisForfait
     * @todo   Implement testMajFraisForfait().
     */
    public function testMajFraisForfait() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::majFraisHorsForfait
     * @todo   Implement testMajFraisHorsForfait().
     */
    public function testMajFraisHorsForfait() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::majNbJustificatifs
     * @todo   Implement testMajNbJustificatifs().
     */
    public function testMajNbJustificatifs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::estPremierFraisMois
     * @todo   Implement testEstPremierFraisMois().
     */
    public function testEstPremierFraisMois() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::dernierMoisSaisi
     * @todo   Implement testDernierMoisSaisi().
     */
    public function testDernierMoisSaisi() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::creeNouvellesLignesFrais
     * @todo   Implement testCreeNouvellesLignesFrais().
     */
    public function testCreeNouvellesLignesFrais() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::creeNouveauFraisHorsForfait
     * @todo   Implement testCreeNouveauFraisHorsForfait().
     */
    public function testCreeNouveauFraisHorsForfait() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::supprimerFraisHorsForfait
     * @todo   Implement testSupprimerFraisHorsForfait().
     */
    public function testSupprimerFraisHorsForfait() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getLesMoisDisponibles
     * @todo   Implement testGetLesMoisDisponibles().
     */
    public function testGetLesMoisDisponibles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getLesVisiteurs
     * @todo   Implement testGetLesVisiteurs().
     */
    public function testGetLesVisiteurs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getLesInfosFicheFrais
     * @todo   Implement testGetLesInfosFicheFrais().
     */
    public function testGetLesInfosFicheFrais() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::majEtatFicheFrais
     * @todo   Implement testMajEtatFicheFrais().
     */
    public function testMajEtatFicheFrais() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::majLibelle
     * @todo   Implement testMajLibelle().
     */
    public function testMajLibelle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::reporterFHF
     * @todo   Implement testReporterFHF().
     */
    public function testReporterFHF() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::montantFF
     * @todo   Implement testMontantFF().
     */
    public function testMontantFF() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::montantFHF
     * @todo   Implement testMontantFHF().
     */
    public function testMontantFHF() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::montantValide
     * @todo   Implement testMontantValide().
     */
    public function testMontantValide() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getMontantVehicule
     * @todo   Implement testGetMontantVehicule().
     */
    public function testGetMontantVehicule() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getQteKm
     * @todo   Implement testGetQteKm().
     */
    public function testGetQteKm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getLesVisiteursVA
     * @todo   Implement testGetLesVisiteursVA().
     */
    public function testGetLesVisiteursVA() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getLesMoisVA
     * @todo   Implement testGetLesMoisVA().
     */
    public function testGetLesMoisVA() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
